### ISSUE TITLE
Readme.md calls out a non-existing file

### ISSUE THREAD

**Issue by evonreis** [RogerLevy/AllegroForthKit#1]
Readme.md recommends running "0 INCLUDE afkit/kit.f" in SwiftForth, but the file doesn't exist in the repository.  "afkit.f" does exist.  Running afkit/afkit.f  fails with message that the [version] word wasn't passed a version number.

**Comment by RogerLevy** [comment]
thanks, i'll update that and look for other outdated info in the readme.

**Comment by RogerLevy** [comment]
it should be `0 0 0 include afkit/afkit.f`

**Comment by evonreis** [comment]
Thanks!

**Comment by RogerLevy** [comment]
Ramen 's readme was way outdated too.  Fixed that hopefully it's accurate.  Please let me know if you continue having trouble.
